### ISSUE TITLE
Replace function relative to actual test

### ISSUE THREAD

**Issue by aertmann** [liady/babel-plugin-module-rewrite#1]
Hey I was trying to use this package to rewrite some paths used in while running tests, but unfortunately the `replaceFunc` is determined from the file babel is processing instead of from where the node process originated.

A fix would be to use replace `process.cwd()` with `process.env.PWD` in https://github.com/liady/babel-plugin-module-rewrite/blob/master/src/index.js#L4

Would that make sense or would that be breaking? If so maybe make it configurable which to use?

Thanks

**Comment by liady** [comment]
@aertmann thank you for your feedback.
I published a new version that supports 'resolveFrom' parameter, that is later going to be `eval`ed.
It defaults to `process.cwd()`.

For example:

``` js
{
  "plugins": [
    ["module-rewrite", {
        "replaceFunc": "./utils/replace-module-paths.js",
        "resolveFrom": "process.env.PWD" // this is going to go through eval(), defaults to "process.cwd()"
    }]
  ]
}
```

Let me know if this works for you.

**Comment by aertmann** [comment]
hey @liady thank you so much, really appreciate it! super quick response and works great 😃
